# docker-compose.yml
version: "3"
services:
  app:
    build: .
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
